### ISSUE TITLE
the Layering Priority is not saved/stored in the Crafts Manager

### ISSUE THREAD

**Issue by ScythiaThe1st** [capyfied/bccm#2]
![image](https://github.com/capyfied/bccm/assets/83371493/6c8b7596-4408-4e21-bef5-bb885e92db7a)
this value refuses to change

**Comment by jimmyG1** [comment]
i don't thank thay are working on this now sadly

**Comment by capyfied** [comment]
Sorry for the delay, I haven't been able to play lately. I'll take a look as soon as I can.

**Comment by capyfied** [comment]
Should be working now.
